name: preview
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  analyzer: ^4.6.0
  args: ^2.3.1
  async: ^2.3.0
  dart_style: ^2.2.3
  device_frame: ^1.1.0
  flutter:
    sdk: flutter
  http: ^0.13.5
  http_parser: ^4.0.1
  http_server: ^1.0.0
  json_rpc_2: ^3.0.2
  mime: ^1.0.2
  path: ^1.8.2
  shelf: ^1.3.2
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1
  shelf_web_socket: ^1.0.2
  stream_channel: ^2.1.0
  vm_service: ^9.3.0
  web_socket_channel: ^2.2.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
