name: idea_widget_preview
description: Widget Preview in IDEA-based development environments.
version: 0.0.4
homepage: https://github.com/andrasferenczi/idea_widget_preview

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: ">=3.0.0"

dependencies:
  analyzer: ^4.6.0
  collection: ^1.16.0
  device_frame: ^1.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  http: ^0.13.5
  intl: ^0.17.0
  meta: ^1.1.8
  shelf: ^1.3.2
  shelf_router: ^1.1.3

dev_dependencies:
  dart_style: ^2.2.3
  lints: ^2.0.0
  test: ^1.0.0

flutter:
  uses-material-design: true
