name: idea_widget_preview
description: Widget Preview in IDEA-based development environments.
version: 0.0.4
homepage: https://github.com/andrasferenczi/idea_widget_preview

environment:
  sdk: '>=3.3.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  analyzer: ^6.4.1
  collection: ^1.18.0
  device_frame: ^1.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  http: ^1.2.1
  intl: ^0.19.0
  meta: ^1.11.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4

dev_dependencies:
  dart_style: ^2.3.6
  lints: ^3.0.0
  test: ^1.25.2

flutter:
  uses-material-design: true
