name: idea_widget_preview
description: Widget Preview in IDEA-based development environments.
version: 0.0.1
homepage: https://github.com/andrasferenczi/idea_widget_preview

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  analyzer: ^4.6.0
  async: ^2.3.0
  collection: ^1.16.0
  dart_style: ^2.2.3
  device_frame: ^1.1.0
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.5+1
  http: ^0.13.5
  http_parser: ^4.0.1
  http_server: ^1.0.0
  intl: ^0.17.0
  meta: ^1.1.8
  path: ^1.8.1
  shelf: ^1.3.2
  shelf_router: ^1.1.3
  shelf_static: ^1.1.1
  shelf_web_socket: ^1.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.0.0

flutter:
  uses-material-design: true
